- README.md
- generate-figures-tables.sh
- renv.lock
Closes #23 
This PR adds a bash script to generate figures and tables, as well as associated documentation. The script was somewhat inspired by organizational choices in our dear old friend, the [OpenPBTA figure generation script](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/figures/generate-figures.sh).
The script is called `generate-figures-tables.sh` and lives in the top-level directory. I ran the script to ensure it worked, and indeed it did! But on the way I had some `renv` problems, and it seemed that `ggforce` hadn't yet been snapshotted into the lockfile, so that is done here as well. The snapshot added some BioC refs which seems fine. 
I also included a bonus line to purge `Rplots.pdf`, which gets created all the time and nobody really knows why (well, I …
> Add script to generate figures and tables

- scripts/TableS1_modality-summary.R
- tables/TableS1-modality-overview.tsv
This PR fixes a bug in the counting for table S1. We were double (and then some!) counting some libraries due to carrying the diagnoses themselves forward int he counting. So, I separated out the code that creates the column for all diagnoses from the code that does the counting. I then join in this table with diagnoses, and counts seem much more sensible now for the multiplexed project!
> Fix Table S1 counts

- README.md
- generate-figures-tables.sh
- sample-info/celltype-reference-metadata.tsv
- scripts/README.md
- scripts/TableS2_cellassign-ref-summary.R
- scripts/figure_setup/sync-metadata.R
- tables/TableS2_cellassign-ref-summary.tsv
Closes #75 
Here I'm adding a supplemental table that includes the list of references created from Panglao for use with CellAssign. For each ScPCA project, I included the reference name and then the list of organs from Panglao used to create the reference. I also included a list of diagnoses for each project to hopefully allow readers to see why some of the organs are included for each project. 
To create the table, I needed to get the ref name for each project from `scpca-celltype-project-metadata.tsv`, so I added that to the `sync-metadata.R` script. I also needed the list of organs, which is stored in the `references` directory in `scpca-nf` that doesn't sync anywhere. I just added that to the repo here in the `sample-info` directory.
> Add table with list of references used from Panglao and associated organs

- analysis/README.md
- analysis/bulk-deconvolution/.gitignore
- analysis/bulk-deconvolution/README.md
- analysis/bulk-deconvolution/scripts/README.md
- analysis/bulk-deconvolution/scripts/sync-salmon-output.R
- renv.lock
- renv/activate.R
- scpca-paper-figures.Rproj
Part 1 of #99 
This PR establishes a directory `analysis/bulk-deconvolution` for the, you guessed it, bulk deconvolution analysis. To keep open the (probably slim but non-zero) possibility that we might do complementary/other scientific analysis here, I decided to nest this in an `analysis` directory where future science can live. 
This directory contains readmes,  `scripts`, and `data` (mostly ignored) directory, and currently one script to sync the quant.sf files. This script uses existing (if present, stops otherwise) metadata files to determine the files to sync, and then syncs to `data/salmon-quant-files` organized in the "usual" project/sample/library order. 
Finally, I also updated the `renv::lock` file by running `renv::restore()` and pretty much agreeing to what it wanted me to …
> Establish deconvolution directory and sync salmon files

- analysis/bulk-deconvolution/README.md
- analysis/bulk-deconvolution/run-deconvolution.sh
- analysis/bulk-deconvolution/scripts/README.md
- analysis/bulk-deconvolution/scripts/calculate-tpm.R
- analysis/bulk-deconvolution/scripts/prepare-data-files.R
- renv.lock
- renv/activate.R
- scripts/figure_setup/sync-reference-files.R
Closes #99 
This PR adds two scripts:
- A script to calculate TPM for a given project and export a TSV file of results
- I use an SCE to help id mapping, and I sum the duplicates as discussed. I use tidyverse and export a tsv here, but there's a good argument to use base R and matrices instead, especially since we'll have to convert these to matrices anyways! But, I enjoy tidyverse so that's what I did. Let me know if we prefer I change that.
- A shell script for the analysis itself
- This currently has a step with a _minimal check_ to download the `quant.sf` files - should this check be more involved? 
- And then, we loop over project directories to calculate a TPM matrix for each. Next up is actual deconvolution.
There are several other updates:
- I updated readmes
- I updated …
> Add script to calculate TPM

- analysis/pseudobulk-bulk-prediction/exploratory-notebooks/README.md
- analysis/pseudobulk-bulk-prediction/exploratory-notebooks/pseudobulk-calculations.Rmd
- analysis/pseudobulk-bulk-prediction/run-prediction.sh
- analysis/pseudobulk-bulk-prediction/scripts/README.md
- analysis/pseudobulk-bulk-prediction/scripts/calculate-pseudobulk.R
- analysis/pseudobulk-bulk-prediction/scripts/calculate-tpm.R
- analysis/pseudobulk-bulk-prediction/scripts/prepare-bulk-counts.R
- analysis/pseudobulk-bulk-prediction/scripts/sync-data-files.R
- renv.lock
Closes #128 
This PR adds a new script to calculate pseudobulk, and a notebook to compare the values to TPM. While there is no horn in this data, there sure is a pretty clean relationship all things considered!
See notebook: [pseudobulk-calculations.nb.html.zip](https://github.com/user-attachments/files/18594135/pseudobulk-calculations.nb.html.zip)
- Here, I use two strategies to convert:
- sum the logcounts
- sum the raw counts and let deseq2 normalize (note there are `renv.lock` changes because of this)
- As part of this, I also included a threshold for dropping genes that have too many zeros - feedback here appreciated!
- I'm aware there's a bit of a wrangling 🎢 at the top and wanted to note that part of this is to be able to get the data needed for the TPM density plots showing genes …
> Calculate and compare pseudobulk measures

- analysis/pseudobulk-bulk-prediction/exploratory-notebooks/compare-pseudobulk-bulk.Rmd
- analysis/pseudobulk-bulk-prediction/run-prediction.sh
- analysis/pseudobulk-bulk-prediction/scripts/calculate-pseudobulk.R
- analysis/pseudobulk-bulk-prediction/scripts/prepare-bulk-counts.R
- analysis/pseudobulk-bulk-prediction/scripts/sync-data-files.R
Towards #144 
This PR updates data preparation scripts to also export tables with the percent of samples each gene is expressed in. These can be used for later filtering. Currently I am exporting these to `data`, but we could send them to `results` instead.
While I was here, I caught a few tiny bugs or mediocre code approaches (e.g. a hardcoded file path that should be an argument!) and made updates accordingly. In particular, I had added various files over time to `data/scpca_data` which somewhat broke the `run_prediction.sh` script for look over projects in that directory. I therefore decided to move files were are not literally ScPCA out of that directory and into its parent `data`. 
I also made a couple file names a bit more consistent with underscores/dashes. Because of these small …
> Export tables of gene expression percentage across samples

- analysis/estimate/.gitignore
- analysis/estimate/README.md
- analysis/estimate/run-estimate-analysis.sh
- analysis/estimate/scripts/README.md
- analysis/estimate/scripts/sync-data-files.R
- analysis/pseudobulk-bulk-prediction/scripts/sync-data-files.R
Closes #152 
This PR establishes the `analysis/estimate` directory with:
- a bash run script
- various readmes where appropriate
- a script to sync data files and export TSV maps we'll need for next steps. This script is largely the same as [this other sync script](https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/analysis/pseudobulk-bulk-prediction/scripts/sync-data-files.R), except it also has parts [like this script](https://github.com/AlexsLemonade/scpca-paper-figures/blob/main/analysis/bulk-deconvolution/scripts/prepare-data-files.R) to create the gene id map tsv.
All output so far is sent to `data/` whose contents are ignored, but it is present with `.gitkeep`. I also fixed a couple typos in the original script I modeled this one after that I found while I was here.
I …
> Establish ESTIMATE analysis directory

- analysis/estimate/run-estimate-analysis.sh
- analysis/estimate/scripts/prepare-expression-data.R
Closes #153 
This PR adds a script to prepare data inputs for ESTIMATE. I ended up deciding to prepare all three data versions (bulk counts, tpm, pseudobulk) in the same script so that we export 1 file per project with a list of three data frames, for each expression flavor. Each of these lists is also formatted to head directly into `tidyestimate`. This also means those directories I created but didn't need yet? ...Well, we don't need them at all in the end!
As part of this, I also had to convert ensembl ids to gene symbols and handle some duplicate symbols. I decided to just sum them up. Notably, none of the duplicate genes are in the marker gene lists, so this shouldn't have much of an effect. Let me know if you wanted to try out other approaches here, but again, I think this won't …
> Add script to prepare data for estimate

- scripts/README.md
- scripts/figure_setup/sync-consensus-celltype-results.R
In preparation to add figures that use the consensus cell type results, here I'm adding a script to the `figure_setup` folder that copies the output from consensus cell typing present in the workflow results bucket from OpenScPCA. 
We already had a script to sync data from S3, but I chose to do this separately since it uses openscpca results and we need an AWS profile. It's also a lot of files so it seemed like it deserved it's own script.
> Add script to sync consensus celltype results 

- renv.lock
- scripts/Fig5A-S6_consensus-cell-type-dotplots.R
- scripts/utils/consensus-celltype-plotting-functions.R
I had some time today, and I couldn't resist trying out `duckplyr`.
I think it works!
I converted most everything back from using `data.table` and `fread` to data frames in the main function, then convert everything to `duckdb_tibble` within the `marker_gene_dotplot` function.
To make it all work, I had to get rid of the `group_by()` statements, converting them to use the new `.by = ` syntax for `mutate()` and `summarize()`. 
~~That was enough to make it work, but reading in all of the gene expression files was still taking a lot of memory. To avoid that, I make a temporary csv file, and read that directly with `read_csv_duckdb()`. This worked amazingly well, and now it takes very little memory, even for Leukemia.
I would have done the same for the initial `consensus_df` tables, but those …
> Try duckplyr for memory efficiency

- analysis/pseudobulk-bulk-prediction/run-prediction.sh
This tiny PR gets rid of `tpm_dir` creation, which isn't needed anymore and should have been removed in #201!
> Get rid of tpm lines

- manuscript-numbers/bulk-analysis-counts.tsv
- scripts/Fig6-FigS7_bulk-analysis.R
Closes #200 
This PR initiates the figure script that will be written for #187 & #195, but currently only takes care of the task in #200. The script does not yet make figures, but it includes a section to create and export a table of counts that will be useful for manuscript writing. This includes per-project numbers of how many samples and gene sets were used, as a well as a row which gives the total counts for convenience. These numbers are included:
- `n_samples_total`: The number of samples identified as potentially suitable for analysis
- `n_samples_low_quality`: The number of samples removed due to low quality
- `n_samples_used`:  This is just `n_samples_total - n_samples_low_quality`, and is the actual number of samples which fed into the analysis in the end
- `n_ora_genesets`: The …
> Add table with bulk analysis manuscript numbers

- reproduce-figures/README.md
- reproduce-figures/prepare-metadata-files.R
Closes #212 
This PR adds a script that converts the portal-wide metadata into tsvs that can be used with our figures and analysis code. I added some documentation for it in the README as well, which references the full instruction file coming up in #217.
> Add metadata script

- analysis/pseudobulk-bulk-prediction/run-prediction.sh
- analysis/pseudobulk-bulk-prediction/scripts/calculate-pseudobulk.R
Closes #241 
The overall goal of these changes is to update code to _not assume_ that all libraries present should be used in analysis. This is because, when others download portal data to reproduce, they should be able to keep all the samples from the portal without having to worry which are actually used in the bulk analysis.
Implementing this turned out to be simpler than I expected! We already have a tsv file with bulk libraries & samples that are used in analysis, so we can use those sample ids to filter down to single-cell/nuclei samples of interest too. The only place this needed to happen was in the script that calculates pseudobulk. After this stage, the scpca data files are no longer used in the code. I added this map file as an input argument to the script and use it to subset …
> Filter to only samples used in analysis

- reproduce-figures/prepare-scpca-portal-data.R
I started working on (edit, wrong link) #211 & #245, beginning with running the code all the way through. So, I found the first and hopefully last set of files we still need to grab - the panglao/cellassign marker gene references used in bulk analysis to make the gene sets. 
This PR adds that step to the data prep script. In addition,  I renamed the existing `reference_dir` variable so we can distinguish between s3_files vs bulk reference directories. I did make this change in VS Code, which ate up many spaces, so I recommend turning off whitespace!
> Sync the panglao references

- reproduce-figures/prepare-scpca-portal-data.R
- reproduce-figures/utils.R
While testing code towards #211 & #245, I hit a bug in the consensus cell type functions at project SCPCP000020. This is a cell line project, so it didn't have the singler cell type column (which is temporarily coded up), but it certainly won't have a consensus annotation either! So, I updated this function to use `NA` values if the column isn't present. 
Additional small changes in the other script are present too:
- Fixed other small bug to change `scpca-data` to `scpca_data`
- I swapped an arg order to match the usage docs (makes it easier for me to work with code) and added a comment for future us.
> Account for SCEs without consensus cell types

- reproduce-figures/prepare-scpca-portal-data.R
- reproduce-figures/utils.R
Closes #259 (if pursued!)
This PR updates our approach for preparing metadata files for reproducibility, according to the scheme I laid out in my opening comment of #259.
To get the full library information we need, I also save and parse bulk metadata TSVs and metadata TSVs for projects with CITE-seq, and handle cellhash samples a bit more carefully to ensure we get their technology information. To get the full sample information we need, I manually add in a table with the information we need.
The result seems to sufficiently match our metadata files! I used these new files, for example, to re-create Table S1 and Table S2. No diff for Table S2 🎉, but for Table S1 these versions of the metadata led to one diff from the table made with our internal metadata - the diagnosis for SCPCP000009 …
> Update metadata parsing

- reproduce-figures/README.md
- reproduce-figures/prepare-scpca-portal-data.R
- reproduce-figures/utils.R
- scripts/utils/consensus-celltype-plotting-functions.R
Closes #253 
This PR makes a couple changes to fully reproducibility of manuscript figures and tables:
- Per the original goal of #253, I updated the cell type column to parse consensus cell types and removed the singler placeholder
- Since the metadata file download is actually a zip file which contains a file `metadata.tsv`, I updated code and docs to account for this. Rather than reading a TSV, I check that it's a ZIP file, unzip it into a dedicated directory in `scratch`, and read in `metadata.tsv` from there.
- When running the dotplot code, I got a factor bug because the `unknown` level was repeated. I am pretty sure we could just safely remove the "unknown"` from this levels vector but I was nervous so instead just put it in a `unique()`! Either way the code is all running now :)
> Reproducibility updates for consensus cell types

- reproduce-figures/utils.R
Closes #283 
As described in the linked issue, we are updating portal metadata such that we may end up with duplicated rows when recreating metadata from the portal since we hardcode a couple samples that are _currently_ missing from the portal-wide tsv. Adding this `unique()` should protect us without having to get into the weeds.
(Worth noting that if we also incorporate bulk metadata into the portal-wide tsv, we could simplify other parsing aspects here, but that really doesn't seem worth the effort since the changes shouldn't _break_ anything!)
> Add a unique
